# Generated by Django 5.0.6 on 2024-07-04 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
