# Generated by Django 5.0.6 on 2024-07-04 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0003_alter_post_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
    ]
