# Generated by Django 5.0.6 on 2024-07-04 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0004_remove_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.FileField(default='comment-images/user.png', upload_to='comment-images'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='postapp.comment'),
            preserve_default=False,
        ),
    ]
